services:

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./dynamodb:/home/dynamodblocal/data:Z"
    working_dir: /home/dynamodblocal

  pythia:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pythia
    ports:
      - "3000:3000"
    depends_on:
      - dynamodb-local
    environment:
      - RUST_LOG=info
      - AWS_ENDPOINT_URL=http://dynamodb-local:8000
      - PYTHIA_RUN_MODE=local
