name: Deploy

on:
  push:
    branches:
      - 'introduce-iac'

permissions:
  id-token: write  # Required for configure-aws-credentials to request JWT from GitHub OIDC
  contents: read

jobs:
  deploy:
    name: Deploy to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.TERRAFORM_AWS_ROLE_ARN }}
          role-session-name: github-actions-pythia-${{ github.ref_name }}-${{ github.run_id }}
          aws-region: us-west-2