name: Build
on:
  pull_request:

env:
  RUST_BACKTRACE: 1

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - i686-unknown-linux-gnu
          - i686-unknown-linux-musl
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-gnu
      fail-fast: false
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt
      - name: cache
        uses: Swatinem/rust-cache@v2
      - name: check_non_default
        run: cargo check --no-default-features
      - name: test
        run: cargo test
      - name: check formatting
        run: cargo fmt -- --check
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-gnu
          - x86_64-pc-windows-msvc
      fail-fast: false
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: cache
        uses: Swatinem/rust-cache@v2
      - name: test
        run: cargo test