name: Teardown

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ECR_REPO_NAME: ecr0

jobs:
  Teardown:
    name: Teardown deployment and infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.TERRAFORM_AWS_ROLE_ARN }}
          role-session-name: github-actions-pythia-${{ github.ref_name }}-${{ github.run_id }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init and apply to destroy ECS Fargate deployment
        run: |
          cd $GITHUB_WORKSPACE/infra/
          terraform fmt
          terraform init \
            -backend-config="bucket=${{ secrets.TERRAFORM_BACKEND_BUCKET }}" \
            -backend-config="key=${{ secrets.TERRAFORM_BACKEND_KEY }}" \
            -backend-config="region=${{ secrets.AWS_REGION }}"
          terraform apply -destroy -auto-approve

      - name: Terraform init and apply to destroy ECR repository
        run: |
          cd $GITHUB_WORKSPACE/infra/ecr/
          terraform fmt
          terraform init \
            -backend-config="bucket=${{ secrets.TERRAFORM_BACKEND_BUCKET }}" \
            -backend-config="key=${{ secrets.TERRAFORM_ECR_BACKEND_KEY }}" \
            -backend-config="region=${{ secrets.AWS_REGION }}"
          terraform apply -destroy -auto-approve

