name: Teardown

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  Teardown:
    name: Teardown ECS Fargate deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.TERRAFORM_AWS_ROLE_ARN }}
          role-session-name: github-actions-pythia-${{ github.ref_name }}-${{ github.run_id }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init and apply to destroy ECS Fargate deployment
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE/infra/
          terraform fmt
          terraform init -reconfigure \
            -backend-config="bucket=${{ secrets.TERRAFORM_BACKEND_BUCKET }}" \
            -backend-config="key=${{ secrets.TERRAFORM_BACKEND_KEY }}" \
            -backend-config="region=${{ secrets.AWS_REGION }}"
          cat > variables.auto.tfvars <<EOF
          aws_region          = "$AWS_REGION"
          az_count            = 1
          container_port      = 1
          image_uri           = "_"
          app_container_name  = "_"
          cloudflare_api_token = "$CLOUDFLARE_API_TOKEN"
          cloudflare_zone_id   = "e5934fef29bb756740a3e348ad2d879e"
          tags = {}
          EOF
          terraform apply -destroy -auto-approve

      - name: Terraform init and apply to destroy ECR repository
        run: |
          cd $GITHUB_WORKSPACE/infra/ecr/
          terraform fmt
          terraform init -reconfigure \
            -backend-config="bucket=${{ secrets.TERRAFORM_BACKEND_BUCKET }}" \
            -backend-config="key=${{ secrets.TERRAFORM_ECR_BACKEND_KEY }}" \
            -backend-config="region=${{ secrets.AWS_REGION }}"
          cat > variables.auto.tfvars <<EOF
          repository_name = "_"
          tags = {}
          EOF
          terraform apply -destroy -auto-approve

